; CAUTION: comment outside of profile like this will be dropped
; profile name should be: unique, not include any of "[]"
; and not equal "profiles"

[local aria2]
; https://developer.chrome.com/extensions/match_patterns
; your can use multiple patterns, simply separate them by space
; some notes:
; *://*/* only matches http or https
; <all_urls> catches more than *://*/* like magnet links
link_patterns = <all_urls>
type = aria2
url = http://127.0.0.1:6800/jsonrpc
token = happythoughts
; anything else will be considered as an option for aria2 as in
; https://aria2.github.io/manual/en/html/aria2c.html#aria2.addUri
; additionally URL of the current page will be sent as referer
max-connection-per-server = 2

[local qBittorrent]
link_patterns = <all_urls>
type = qbt
url = http://127.0.0.1:8080
; you can omit this if you have the web ui in the same browser
; since it uses cookie to auth
username = user
password = pass
; anything else will be considered as an option for qBittorrent as in
; https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#add-new-torrent
paused = true
